### ISSUE TITLE
Elevation settings

### ISSUE THREAD

**Issue by hawesn99** [mholow/gsp-r10-adapter#18]
If I change the elevation settings in the text file to say 4600, and then also change the elevation in GSPro to 4600, is that ok or would the elevation impact to ball distance be exaggerated?

**Comment by mholow** [comment]
I would personally stick to only setting elevation in gspro.  I understand this is confusing, but the only reason the elevation is in the settings file is because it is part of the official device setup interface. However, most people have been reporting that it does not make too much of an impact on readings. This makes sense to me because elevation matters most on the carry calculations, which are done in gspro

**Comment by hawesn99** [comment]
Great thanks
